name: cron
description: A time-based job scheduler similar to cron. Run tasks periodically at fixed times or intervals.
version: 0.2.0
author: Istvan Soos <istvan.soos@agilord.com>

homepage: https://github.com/agilord/cron

environment:
  sdk: '>=2.0.0 <3.0.0'
